version: "3"
services:
  linguist:
    user: node
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./build:/mnt/builder/build
      - ./thirdparty/bergamot/build:/mnt/builder/thirdparty/bergamot/build
    cap_add:
      - SYS_ADMIN

  bergamot:
    user: node
    build:
      context: ./thirdparty/bergamot
    volumes:
      - ./thirdparty/bergamot/build:/mnt/bergamot/build
      # Persistent cache for fast builds
      - ./.local/docker-volumes/bergamot-translator:/mnt/bergamot/bergamot-translator
    cap_add:
      - SYS_ADMIN