name: Release

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

# TODO: add job to upload new versions to stores with API
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build

        # Place to stop for DRY run
      - name: Build XPI file for firefox
        working-directory: "./build"
        env:
          AMO_KEY: ${{ secrets.AMO_KEY }}
          AMO_SECRET: ${{ secrets.AMO_SECRET }}
        run: |
          mkdir ./AMO
          npx web-ext sign --api-key "$AMO_KEY" --api-secret "$AMO_SECRET" --id "{e3fc2d33-09fc-4fe8-9331-d0a464698035}" --source-dir ./firefox --artifacts-dir ./AMO
          mv AMO/*.xpi AMO/linguist.xpi

      - name: Publish release on GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/AMO/linguist.xpi
            build/linguist.crx
            build/*.zip

      - name: Build static files for GitHub Pages
        working-directory: "./build"
        run: |
          mkdir ./site
          node ../scripts/genCrxUpdateManifest.js > ./site/chromium_updates.xml
          # TODO: build index.html with landing page

      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: noreply@example.com
          build_dir: "./build/site"
          branch: gh-pages
